Feature comments
DM-student/java-explore-with-me pull request #6
Opened 2023-08-05 00:15 UTC by DM-student

Здравствуйте!

Я постарался реализовать постман-тесты максимально автономными, с используя за основу тесты для основного сервиса.

Я очень надеюсь что проект вас удовлетворит, я очень старался.

Надеюсь что дадите поблажку по причине того, что у меня сроки уже наступили и я возможно не успею на ещё одну итерацию попасть.

2023-08-06 10:28 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Но я хотел бы получить ответы на вопросы по некотрым замечаниям, после чего смогу принять работу!

Желаю удачи!

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/dto/CommentDto.java
> +        return true;
Тогда это можно существенно упростить, так как метод небольшой, то можно вернуть

```java
return id != null && edited != null && text != null && !text.isBlank();
```

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/dto/CommentDto.java
> +        return true;
Тоже можно одним `return` все организовать

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/dto/CommentDto.java
> +    private static final DateTimeFormatter formatter = MainServiceDtoConstants.DATE_TIME_FORMATTER;
Зачем это сохранять сюда, если это уже существует где-то как константа?
Почему нельзя к этому просто обращаться по необходимости?

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +        return output.get(0);
советовал бы воспользоваться здесь `Stream API`:

```java
return mapComments(jdbcTemplate.queryForRowSet("SELECT * FROM comments WHERE id = ?;", id))
           .stream()
           .findFirst()
           .orElseThrow(() -> new NotFoundError("Comment not found.", id));
```

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +        return mapComments(rs).get(0);
Аналогично, советовал бы воспользоваться Stream API

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +        return getComment(comment.getId());
не стоит делать лишний запрос в СУБД, если мы мржем восстановить объект и по имеющимся данным.
Более того, стоит вопрос нужно ли нам вообще возвращать целый объект, если по факту мы изменяем одно поле.

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +                "OFFSET ?;";
Лучше вместо оператора `LIMIT`, который не определен в стандарте `SQL` использовать оператор `FETCH`

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +                "OFFSET ?;";
Аналогично тому, что написал ниже

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +    private static final DateTimeFormatter formatter = MainServiceDtoConstants.DATE_TIME_FORMATTER;
Зачем это сюда копировать?

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/controllers/CommentController.java
> +public class CommentController {
Мне кажется не лучшей идеей объединять в один контроллер админские и пользовательские методы.
Это потенциально может привести к тому, что рано или поздно (при доработке или рефакторинге) пользователь получит случайно админские права, которые не должен.

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/controllers/CommentController.java
> +    }
Методам стоит давать нормальные названия, а не по имени HTTP-методов

2023-08-06 10:28 UTC, LexLippi commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/services/CommentService.java
> +    DateTimeFormatter formatter = MainServiceDtoConstants.DATE_TIME_FORMATTER;
1. Почему без модификаторов доступа?
2. Зачем это в принципе копировать в сервис?

2023-08-06 12:45 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/dto/CommentDto.java
> +        return true;
Ответил выше.

2023-08-06 12:45 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/dto/CommentDto.java
> +        return true;
Это безусловно так, но я предпочитаю читаемость. В таком формате легче будет добавить новое поле и  целом код выглядит более читаемым.

2023-08-06 12:48 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/services/CommentService.java
> +    DateTimeFormatter formatter = MainServiceDtoConstants.DATE_TIME_FORMATTER;
Я создаю "ссылку" на эту константу, причина проста: Хочу чтобы вместо длинного `MainServiceDtoConstants.DATE_TIME_FORMATTER` у меня был маленький `formatter`.

2023-08-06 12:50 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +    private static final DateTimeFormatter formatter = MainServiceDtoConstants.DATE_TIME_FORMATTER;
Я создаю "ссылку" на эту константу, причина проста: Хочу чтобы вместо длинного `MainServiceDtoConstants.DATE_TIME_FORMATTER` у меня был маленький и удобный `formatter`.

2023-08-06 12:58 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/controllers/CommentController.java
> +    }
Исправил.

2023-08-06 13:00 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/controllers/CommentController.java
> +public class CommentController {
Я не думаю, что такая проблема возникнуть может, ибо разные эндпоинты у подобных запросов, да и админские методы я пометил словом админ в названии.

2023-08-06 13:02 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +                "OFFSET ?;";
К сожалению мне другой ревьювер не намекнул на это и я во всём проекте использовал именно limit и offset, довольствуясь возможностями posgres.

2023-08-06 13:02 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +                "OFFSET ?;";
На рефакторинг проекта у меня времени совсем нет, а менять лишь один класс - я считаю что глупо.

2023-08-06 13:03 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +                "OFFSET ?;";
Ответил выше.

2023-08-06 13:09 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +        return output.get(0);
Сделал так.

2023-08-06 13:09 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +        return mapComments(rs).get(0);
Угу.

2023-08-06 13:20 UTC, DM-student commented on main-service/main-service-server/src/main/java/ru/practicum/main_service/server/database/CommentDatabase.java
> +        return getComment(comment.getId());
Добавил 'returning' чтобы в этом же запросе получать ответ.

2023-08-06 13:25 UTC, DM-student commented
В целом ваши замечания применимы ко всему проекту, но **другого ревьювера** устроило всё. Сейчас уже у меня просто банально нет времени на рефакторинг и поиск "похожих проблем" в остальном проекте.

Понимаю что проект не идеален, но времени у меня уже вообще нет. На вопросы ответил. Надеюсь на ваше понимание.

2023-08-07 07:36 UTC, LexLippi commented
Привет!

Хороший проект, у каждого из ревьюеров свой взгляд, поэтому не буду приставать к тебе с дополнительными замечаниями. Просто в реальной разработке важно это учитывать, и эти вопросы хотя бы себе задавать, надо всегда взвешивать плюсы и минусы тех или иных технических решений, и хотя для себя понимать, почему я делаю так, а не иначе.

В общем, поздравляю с окончанием курса `Java`-разработчик и успешной сдачей диплома!

Надеюсь наш курс в целом, и мои ревью в частности были полезны для тебя!

2023-08-08 17:43 UTC, merged